"""Recommendation Engine contract."""

from italian_energy.recommendation.engine import (
    CandidateDiscountProfile,
    CandidateTariffKind,
    DeterministicRecommendationEngine,
    DiscountPolicy,
    PriceRisk,
    Recommendation,
    RecommendationCandidate,
    RecommendationCandidateEvidence,
    RecommendationDecision,
    RecommendationEngine,
    RecommendationError,
    RecommendationExclusion,
    RecommendationExclusionCode,
    RecommendationPreferences,
    RecommendationReasonCode,
    RecommendationRequest,
    RecommendationTariffPreference,
    TariffPreference,
    TemporaryDiscountPolicy,
    VolatilityTolerance,
    indexed_tariff_is_capped,
)

__all__ = [
    "CandidateDiscountProfile",
    "CandidateTariffKind",
    "DeterministicRecommendationEngine",
    "DiscountPolicy",
    "PriceRisk",
    "Recommendation",
    "RecommendationCandidate",
    "RecommendationCandidateEvidence",
    "RecommendationDecision",
    "RecommendationEngine",
    "RecommendationError",
    "RecommendationExclusion",
    "RecommendationExclusionCode",
    "RecommendationPreferences",
    "RecommendationReasonCode",
    "RecommendationRequest",
    "RecommendationTariffPreference",
    "TariffPreference",
    "TemporaryDiscountPolicy",
    "VolatilityTolerance",
    "indexed_tariff_is_capped",
]
